/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.zvelo.msg.QueryResult');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.zvelo.msg.DataSet');
goog.require('proto.zvelo.msg.QueryStatus');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zvelo.msg.QueryResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zvelo.msg.QueryResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.zvelo.msg.QueryResult.displayName = 'proto.zvelo.msg.QueryResult';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zvelo.msg.QueryResult.prototype.toObject = function(opt_includeInstance) {
  return proto.zvelo.msg.QueryResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zvelo.msg.QueryResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zvelo.msg.QueryResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    responseDataset: (f = msg.getResponseDataset()) && proto.zvelo.msg.DataSet.toObject(includeInstance, f),
    url: jspb.Message.getFieldWithDefault(msg, 8, ""),
    queryStatus: (f = msg.getQueryStatus()) && proto.zvelo.msg.QueryStatus.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zvelo.msg.QueryResult}
 */
proto.zvelo.msg.QueryResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zvelo.msg.QueryResult;
  return proto.zvelo.msg.QueryResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zvelo.msg.QueryResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zvelo.msg.QueryResult}
 */
proto.zvelo.msg.QueryResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 7:
      var value = new proto.zvelo.msg.DataSet;
      reader.readMessage(value,proto.zvelo.msg.DataSet.deserializeBinaryFromReader);
      msg.setResponseDataset(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 10:
      var value = new proto.zvelo.msg.QueryStatus;
      reader.readMessage(value,proto.zvelo.msg.QueryStatus.deserializeBinaryFromReader);
      msg.setQueryStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zvelo.msg.QueryResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zvelo.msg.QueryResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zvelo.msg.QueryResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zvelo.msg.QueryResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResponseDataset();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.zvelo.msg.DataSet.serializeBinaryToWriter
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getQueryStatus();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.zvelo.msg.QueryStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.zvelo.msg.QueryResult.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.zvelo.msg.QueryResult.prototype.setRequestId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional DataSet response_dataset = 7;
 * @return {?proto.zvelo.msg.DataSet}
 */
proto.zvelo.msg.QueryResult.prototype.getResponseDataset = function() {
  return /** @type{?proto.zvelo.msg.DataSet} */ (
    jspb.Message.getWrapperField(this, proto.zvelo.msg.DataSet, 7));
};


/** @param {?proto.zvelo.msg.DataSet|undefined} value */
proto.zvelo.msg.QueryResult.prototype.setResponseDataset = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.zvelo.msg.QueryResult.prototype.clearResponseDataset = function() {
  this.setResponseDataset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.zvelo.msg.QueryResult.prototype.hasResponseDataset = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string url = 8;
 * @return {string}
 */
proto.zvelo.msg.QueryResult.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.zvelo.msg.QueryResult.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional QueryStatus query_status = 10;
 * @return {?proto.zvelo.msg.QueryStatus}
 */
proto.zvelo.msg.QueryResult.prototype.getQueryStatus = function() {
  return /** @type{?proto.zvelo.msg.QueryStatus} */ (
    jspb.Message.getWrapperField(this, proto.zvelo.msg.QueryStatus, 10));
};


/** @param {?proto.zvelo.msg.QueryStatus|undefined} value */
proto.zvelo.msg.QueryResult.prototype.setQueryStatus = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.zvelo.msg.QueryResult.prototype.clearQueryStatus = function() {
  this.setQueryStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.zvelo.msg.QueryResult.prototype.hasQueryStatus = function() {
  return jspb.Message.getField(this, 10) != null;
};


