/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.zvelo.msg.QueryStatus');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.zvelo.msg.Status');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zvelo.msg.QueryStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zvelo.msg.QueryStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.zvelo.msg.QueryStatus.displayName = 'proto.zvelo.msg.QueryStatus';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zvelo.msg.QueryStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.zvelo.msg.QueryStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zvelo.msg.QueryStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zvelo.msg.QueryStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    complete: jspb.Message.getFieldWithDefault(msg, 1, false),
    error: (f = msg.getError()) && proto.zvelo.msg.Status.toObject(includeInstance, f),
    fetchCode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    location: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zvelo.msg.QueryStatus}
 */
proto.zvelo.msg.QueryStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zvelo.msg.QueryStatus;
  return proto.zvelo.msg.QueryStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zvelo.msg.QueryStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zvelo.msg.QueryStatus}
 */
proto.zvelo.msg.QueryStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setComplete(value);
      break;
    case 2:
      var value = new proto.zvelo.msg.Status;
      reader.readMessage(value,proto.zvelo.msg.Status.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFetchCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zvelo.msg.QueryStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zvelo.msg.QueryStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zvelo.msg.QueryStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zvelo.msg.QueryStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComplete();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.zvelo.msg.Status.serializeBinaryToWriter
    );
  }
  f = message.getFetchCode();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional bool complete = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.zvelo.msg.QueryStatus.prototype.getComplete = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.zvelo.msg.QueryStatus.prototype.setComplete = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional Status error = 2;
 * @return {?proto.zvelo.msg.Status}
 */
proto.zvelo.msg.QueryStatus.prototype.getError = function() {
  return /** @type{?proto.zvelo.msg.Status} */ (
    jspb.Message.getWrapperField(this, proto.zvelo.msg.Status, 2));
};


/** @param {?proto.zvelo.msg.Status|undefined} value */
proto.zvelo.msg.QueryStatus.prototype.setError = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.zvelo.msg.QueryStatus.prototype.clearError = function() {
  this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.zvelo.msg.QueryStatus.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 fetch_code = 3;
 * @return {number}
 */
proto.zvelo.msg.QueryStatus.prototype.getFetchCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.zvelo.msg.QueryStatus.prototype.setFetchCode = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string location = 4;
 * @return {string}
 */
proto.zvelo.msg.QueryStatus.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.zvelo.msg.QueryStatus.prototype.setLocation = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


