# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zvelo/msg/apiv1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zvelo.msg import query_pb2 as zvelo_dot_msg_dot_query__pb2
from zvelo.msg import suggest_pb2 as zvelo_dot_msg_dot_suggest__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zvelo/msg/apiv1.proto',
  package='zvelo.msg',
  syntax='proto3',
  serialized_pb=_b('\n\x15zvelo/msg/apiv1.proto\x12\tzvelo.msg\x1a\x15zvelo/msg/query.proto\x1a\x17zvelo/msg/suggest.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\xd3\x02\n\x05\x41PIv1\x12P\n\x05Query\x12\x18.zvelo.msg.QueryRequests\x1a\x17.zvelo.msg.QueryReplies\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v1/query:\x01*\x12V\n\x06Result\x12\x14.zvelo.msg.RequestID\x1a\x16.zvelo.msg.QueryResult\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/query/{request_id}\x12P\n\x07Suggest\x12\x15.zvelo.msg.Suggestion\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0b/v1/suggest:\x01*\x12N\n\x06Stream\x12\x16.google.protobuf.Empty\x1a\x16.zvelo.msg.QueryResult\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/stream0\x01\x42\x0eZ\x0czvelo.io/msgb\x06proto3')
  ,
  dependencies=[zvelo_dot_msg_dot_query__pb2.DESCRIPTOR,zvelo_dot_msg_dot_suggest__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\014zvelo.io/msg'))

_APIV1 = _descriptor.ServiceDescriptor(
  name='APIv1',
  full_name='zvelo.msg.APIv1',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=144,
  serialized_end=483,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='zvelo.msg.APIv1.Query',
    index=0,
    containing_service=None,
    input_type=zvelo_dot_msg_dot_query__pb2._QUERYREQUESTS,
    output_type=zvelo_dot_msg_dot_query__pb2._QUERYREPLIES,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\016\"\t/v1/query:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='Result',
    full_name='zvelo.msg.APIv1.Result',
    index=1,
    containing_service=None,
    input_type=zvelo_dot_msg_dot_query__pb2._REQUESTID,
    output_type=zvelo_dot_msg_dot_query__pb2._QUERYRESULT,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\030\022\026/v1/query/{request_id}')),
  ),
  _descriptor.MethodDescriptor(
    name='Suggest',
    full_name='zvelo.msg.APIv1.Suggest',
    index=2,
    containing_service=None,
    input_type=zvelo_dot_msg_dot_suggest__pb2._SUGGESTION,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\020\"\013/v1/suggest:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='zvelo.msg.APIv1.Stream',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=zvelo_dot_msg_dot_query__pb2._QUERYRESULT,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\014\022\n/v1/stream')),
  ),
])
_sym_db.RegisterServiceDescriptor(_APIV1)

DESCRIPTOR.services_by_name['APIv1'] = _APIV1

# @@protoc_insertion_point(module_scope)
