// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zvelo/msg/apiv1.proto

/*
	Package msg is a generated protocol buffer package.

	zveloAPI

	It is generated from these files:
		zvelo/msg/apiv1.proto
		zvelo/msg/category.proto
		zvelo/msg/dataset.proto
		zvelo/msg/query.proto
		zvelo/msg/suggest.proto

	It has these top-level messages:
		DataSet
		RequestID
		QueryStatus
		QueryResult
		URLContent
		QueryRequests
		QueryReply
		QueryReplies
		Suggestion
*/
package msg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf2 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for APIv1 service

type APIv1Client interface {
	// Create new query
	Query(ctx context.Context, in *QueryRequests, opts ...grpc.CallOption) (*QueryReplies, error)
	// Results of active or unexpired query
	Result(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*QueryResult, error)
	// Suggest new datasets for a URL
	Suggest(ctx context.Context, in *Suggestion, opts ...grpc.CallOption) (*google_protobuf2.Empty, error)
}

type aPIv1Client struct {
	cc *grpc.ClientConn
}

func NewAPIv1Client(cc *grpc.ClientConn) APIv1Client {
	return &aPIv1Client{cc}
}

func (c *aPIv1Client) Query(ctx context.Context, in *QueryRequests, opts ...grpc.CallOption) (*QueryReplies, error) {
	out := new(QueryReplies)
	err := grpc.Invoke(ctx, "/zvelo.msg.APIv1/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIv1Client) Result(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*QueryResult, error) {
	out := new(QueryResult)
	err := grpc.Invoke(ctx, "/zvelo.msg.APIv1/Result", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIv1Client) Suggest(ctx context.Context, in *Suggestion, opts ...grpc.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc.Invoke(ctx, "/zvelo.msg.APIv1/Suggest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for APIv1 service

type APIv1Server interface {
	// Create new query
	Query(context.Context, *QueryRequests) (*QueryReplies, error)
	// Results of active or unexpired query
	Result(context.Context, *RequestID) (*QueryResult, error)
	// Suggest new datasets for a URL
	Suggest(context.Context, *Suggestion) (*google_protobuf2.Empty, error)
}

func RegisterAPIv1Server(s *grpc.Server, srv APIv1Server) {
	s.RegisterService(&_APIv1_serviceDesc, srv)
}

func _APIv1_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIv1Server).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zvelo.msg.APIv1/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIv1Server).Query(ctx, req.(*QueryRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIv1_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIv1Server).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zvelo.msg.APIv1/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIv1Server).Result(ctx, req.(*RequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIv1_Suggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Suggestion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIv1Server).Suggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zvelo.msg.APIv1/Suggest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIv1Server).Suggest(ctx, req.(*Suggestion))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIv1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zvelo.msg.APIv1",
	HandlerType: (*APIv1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _APIv1_Query_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _APIv1_Result_Handler,
		},
		{
			MethodName: "Suggest",
			Handler:    _APIv1_Suggest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zvelo/msg/apiv1.proto",
}

func init() { proto.RegisterFile("zvelo/msg/apiv1.proto", fileDescriptorApiv1) }

var fileDescriptorApiv1 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xad, 0x2a, 0x4b, 0xcd,
	0xc9, 0xd7, 0xcf, 0x2d, 0x4e, 0xd7, 0x4f, 0x2c, 0xc8, 0x2c, 0x33, 0xd4, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x04, 0x0b, 0xeb, 0xe5, 0x16, 0xa7, 0x4b, 0x21, 0xa9, 0x28, 0x2c, 0x4d, 0x2d,
	0xaa, 0x84, 0xa8, 0x90, 0x12, 0x47, 0x08, 0x17, 0x97, 0xa6, 0xa7, 0xa7, 0x16, 0x97, 0x40, 0x25,
	0x64, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0x41, 0xc6, 0xe9, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24,
	0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x65, 0xa5, 0xa1, 0xb2, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e,
	0x6a, 0x6e, 0x41, 0x09, 0xd4, 0x4c, 0xa3, 0x66, 0x26, 0x2e, 0x56, 0xc7, 0x00, 0xcf, 0x32, 0x43,
	0xa1, 0x00, 0x2e, 0xd6, 0x40, 0x90, 0x65, 0x42, 0x12, 0x7a, 0x70, 0x97, 0xe8, 0x81, 0x45, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x8a, 0xa5, 0xc4, 0x31, 0x65, 0x0a, 0x72, 0x32, 0x53, 0x8b,
	0x95, 0x44, 0x9a, 0x2e, 0x3f, 0x99, 0xcc, 0xc4, 0xa7, 0xc4, 0xa9, 0x5f, 0x66, 0x08, 0x71, 0xb2,
	0x15, 0xa3, 0x96, 0x50, 0x18, 0x17, 0x5b, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x90, 0x08, 0x92,
	0x46, 0xa8, 0x69, 0x9e, 0x2e, 0x52, 0x62, 0x98, 0xc6, 0x81, 0x54, 0x2b, 0xc9, 0x81, 0x4d, 0x93,
	0x10, 0x12, 0x83, 0x9b, 0xa6, 0x5f, 0x5d, 0x04, 0xd1, 0x15, 0x9f, 0x99, 0x52, 0x2b, 0x14, 0xc0,
	0xc5, 0x1e, 0x0c, 0xf1, 0xbf, 0x90, 0x28, 0x92, 0x11, 0x50, 0xb1, 0xcc, 0xfc, 0x3c, 0x29, 0x31,
	0x3d, 0x88, 0x9f, 0xf5, 0x60, 0x7e, 0xd6, 0x73, 0x05, 0xf9, 0x59, 0x49, 0x0c, 0x6c, 0xb2, 0x80,
	0x12, 0x37, 0xc8, 0x64, 0x68, 0x18, 0x5a, 0x31, 0x6a, 0x39, 0xd9, 0x5d, 0x78, 0x28, 0xc7, 0x70,
	0xe3, 0xa1, 0x1c, 0xc3, 0x83, 0x87, 0x72, 0x8c, 0x1f, 0x1e, 0xca, 0x31, 0x36, 0x3c, 0x92, 0x63,
	0x5c, 0xf1, 0x48, 0x8e, 0xf1, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92,
	0x63, 0x7c, 0xf1, 0x48, 0x8e, 0xe1, 0xc3, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0xa2, 0x78,
	0x20, 0xf6, 0x66, 0x82, 0xa3, 0x23, 0x89, 0x0d, 0x6c, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x01, 0x1c, 0xd2, 0xd4, 0xdb, 0x01, 0x00, 0x00,
}
