package msg

// CategoryLong is a map from Category to long string names
var CategoryLong = map[Category]string{
	Category_UNKNOWN:      "Unknown Category",
	Category_ABORTION_4:   "Abortion",
	Category_PROCHOICE_4:  "Abortion Pro Choice",
	Category_PROLIFE_4:    "Abortion Pro Life",
	Category_PG13_4:       "Child Inappropriate",
	Category_GAMBLING_4:   "Gambling",
	Category_GAY_4:        "Gay, Lesbian or Bisexual",
	Category_LINGERIE_4:   "Lingerie, Suggestive & Pinup",
	Category_NUDITY_4:     "Nudity",
	Category_PORN_4:       "Pornography",
	Category_PROFANITY_4:  "Profanity",
	Category_RATEDR_4:     "R-Rated",
	Category_SEX_4:        "Sex & Erotic",
	Category_EDSEX_4:      "Sex Education",
	Category_TOBACCO_4:    "Tobacco",
	Category_MIL_4:        "Military",
	Category_VIOLENCE_4:   "Violence",
	Category_WEAPONS_4:    "Weapons",
	Category_AGGRESSIVE_4: "Aggressive - Other",
	Category_FINEART_4:    "Fine Art",
	Category_ART_4:        "Arts - Other",
	Category_AUTOPARTS_4:  "Auto Parts",
	Category_AUTOREPAIR_4: "Auto Repair",
	Category_BUYSELLCAR_4: "Buying/Selling Cars",
	Category_CARCULTURE_4: "Car Culture",
	Category_CPO_4:        "Certified Pre-Owned",
	Category_CARCONVERT_4: "Convertible",
	Category_COUPE_4:      "Coupe",
	Category_CUV_4:        "Crossover",
	Category_DIESEL_4:     "Diesel",
	Category_EVEHICLE_4:   "Electric Vehicle",
	Category_HATCHBACK_4:  "Hatchback",
	Category_HYBRIDCAR_4:  "Hybrid",
	Category_LUXURYCAR_4:  "Luxury",
	Category_MINIVAN_4:    "MiniVan",
	Category_MOTORCYCLE_4: "Motorcycles",
	Category_OFFROAD_4:    "Off-Road Vehicles",
	Category_PERFCAR_4:    "Performance Vehicles",
	Category_PICKUP_4:     "Pickup",
	Category_ROADASSIST_4: "Road-Side Assistance",
	Category_SEDAN_4:      "Sedan",
	Category_TRUCK_4:      "Trucks & Accessories",
	Category_VINTAGECAR_4: "Vintage Cars",
	Category_WAGON_4:      "Wagon",
	Category_AUTOMOTIVE_4: "Automotive - Other",
	Category_AG_4:         "Agriculture",
	Category_BIOTECH_4:    "Biotechnology",
	Category_BIZSOFT_4:    "Business Software",
	Category_BUILD_4:      "Construction",
	Category_FORESTRY_4:   "Forestry",
	Category_BIZGOV_4:     "Government",
	Category_NATURE_4:     "Green Solutions & Conservation",
	Category_FURNITURE_4:  "Home & Office Furnishings",
	Category_HR_4:         "Human Resources",
	Category_MFG_4:        "Manufacturing",
	Category_MKTG_4:       "Marketing Services",
	Category_METAL_4:      "Metals",
	Category_PHYSEC_4:     "Physical Security",
	Category_BIZPROD_4:    "Productivity",
	Category_RETIREHOME_4: "Retirement Homes & Assisted Living",
	Category_SHIPPING_4:   "Shipping & Logistics",
	Category_BUSINESS_4:   "Business - Other",
	Category_JOBADVICE_4:  "Career Advice",
	Category_CAREERPLAN_4: "Career Planning",
	Category_COLJOB_4:     "College",
	Category_FINAID_4:     "Financial Aid",
	Category_JOBFAIR_4:    "Job Fairs",
	Category_JOBSEARCH_4:  "Job Search",
	Category_NURSING_4:    "Nursing",
	Category_RESUME_4:     "Resume Writing/Advice",
	Category_SCHOLAR_4:    "Scholarships",
	Category_TELCOMMUTE_4: "Telecommuting",
	Category_MILJOBS_4:    "U.S. Military",
	Category_CAREER_4:     "Careers - Other",
	Category_CHILDABUSE_4: "Child Abuse Images",
	Category_CRIMSKILL_4:  "Criminal Skills",
	Category_HACKING_4:    "Hacking",
	Category_HATE_4:       "Hate Speech",
	Category_DRUGS_4:      "Illegal Drugs",
	Category_POT_4:        "Marijuana",
	Category_WAREZ_4:      "Piracy & Copyright Theft",
	Category_EDUCHEAT_4:   "School Cheating",
	Category_SELFHARM_4:   "Self Harm",
	Category_TORRENT_4:    "Torrent Repository",
	Category_CRIM_4:       "Criminal Activities - Other",
	Category_ANON_4:       "Anonymizer",
	Category_CHAT_4:       "Chat",
	Category_GROUPS_4:     "Community Forums",
	Category_IM_4:         "Instant Messenger",
	Category_LOGIN_4:      "Login Screens",
	Category_BLOG_4:       "Personal Pages & Blogs",
	Category_PHOTO_4:      "Photo Sharing",
	Category_PROFNET_4:    "Professional Networking",
	Category_REDIR_4:      "Redirect",
	Category_SOCNET_4:     "Social Networking",
	Category_SMS_4:        "Text Messaging & SMS",
	Category_TRANSLATOR_4: "Translator",
	Category_EMAIL_4:      "Web-based Email",
	Category_CARDS_4:      "Web-based Greeting Cards",
	Category_EDU712_4:     "7-12 Education",
	Category_ADULTEDU_4:   "Adult Education",
	Category_ARTHISTORY_4: "Art History",
	Category_COLADMIN_4:   "College Administration",
	Category_COLLIFE_4:    "College Life",
	Category_DLEARNING_4:  "Distance Learning",
	Category_SCHOOL_4:     "Educational Institutions",
	Category_EDSTUDIES_4:  "Educational Materials & Studies",
	Category_ENGLISH_4:    "English as a 2nd Language",
	Category_GRADSCHOOL_4: "Graduate School",
	Category_HOMESCHOOL_4: "Homeschooling",
	Category_HOMEWORK_4:   "Homework/Study Tips",
	Category_K6EDU_4:      "K-6 Educators",
	Category_LANGUAGE_4:   "Language Learning",
	Category_BOOK_4:       "Literature & Books",
	Category_PRIVSCHOOL_4: "Private School",
	Category_REF_4:        "Reference Materials & Maps",
	Category_SPED_4:       "Special Education",
	Category_BIZEDU_4:     "Studying Business",
	Category_TUTOR_4:      "Tutoring",
	Category_WIKI_4:       "Wikis",
	Category_EDU_4:        "Education - Other",
	Category_ENTNEWS_4:    "Entertainment News & Celebrity Sites",
	Category_VENUE_4:      "Entertainment Venues & Events",
	Category_HUMOR_4:      "Humor",
	Category_MOVIE_4:      "Movies",
	Category_MUSIC_4:      "Music",
	Category_AUDIO_4:      "Streaming & Downloadable Audio",
	Category_VIDEO_4:      "Streaming & Downloadable Video",
	Category_TV_4:         "Television",
	Category_ENT_4:        "Entertainment - Other",
	Category_ADOPT_4:      "Adoption",
	Category_TODDLER_4:    "Babies and Toddlers",
	Category_PRESCHOOL_4:  "Daycare/Pre School",
	Category_ELDERCARE_4:  "Eldercare",
	Category_FAMILYNET_4:  "Family Internet",
	Category_K6PARENT_4:   "Parenting",
	Category_PARENTEEN_4:  "Parenting Teens",
	Category_PREGNANCY_4:  "Pregnancy",
	Category_SNKPARENT_4:  "Special Needs Kids",
	Category_FAMILY_4:     "Family & Parenting - Other",
	Category_ACCESSORY_4:  "Accessories",
	Category_BEAUTY_4:     "Beauty",
	Category_BODYART_4:    "Body Art",
	Category_CLOTHING_4:   "Clothing",
	Category_FASHNMISC_4:  "Fashion",
	Category_JEWELRY_4:    "Jewelry",
	Category_SWIMSUIT_4:   "Swimsuits",
	Category_FASHION_4:    "Fashion - Other",
	Category_ACCTG_4:      "Accounting",
	Category_BANK_4:       "Banking",
	Category_BGNINVEST_4:  "Beginning Investing",
	Category_LOAN_4:       "Credit/Debt & Loans",
	Category_FINNEWS_4:    "Financial News",
	Category_FINPLAN_4:    "Financial Planning",
	Category_HEDGEFUND_4:  "Hedge Fund",
	Category_INSURANCE_4:  "Insurance",
	Category_INVEST_4:     "Investing",
	Category_MUTUALFUND_4: "Mutual Funds",
	Category_QUOTES_4:     "Online Financial Tools & Quotes",
	Category_FINANCEOPT_4: "Options",
	Category_RETIREPLAN_4: "Retirement Planning",
	Category_STOCKS_4:     "Stocks",
	Category_TAX_4:        "Tax Planning",
	Category_FINANCE_4:    "Finance - Other",
	Category_USFOOD_4:     "American Cuisine",
	Category_BBQ_4:        "Barbecues & Grilling",
	Category_CAJUNFOOD_4:  "Cajun/Creole",
	Category_ZHFOOD_4:     "Chinese Cuisine",
	Category_COCKTAIL_4:   "Cocktails/Beer",
	Category_COFFEE_4:     "Coffee/Tea",
	Category_CUISINE_4:    "Cuisine-Specific",
	Category_DESSERT_4:    "Desserts & Baking",
	Category_DININGOUT_4:  "Dining Out",
	Category_FUDALLERGY_4: "Food Allergies",
	Category_FRFOOD_4:     "French Cuisine",
	Category_LOWFAT_4:     "Health/Lowfat Cooking",
	Category_ITFOOD_4:     "Italian Cuisine",
	Category_JAFOOD_4:     "Japanese Cuisine",
	Category_MXFOOD_4:     "Mexican Cuisine",
	Category_VEGAN_4:      "Vegan",
	Category_VEGETARIAN_4: "Vegetarian",
	Category_WINE_4:       "Wine",
	Category_FOOD_4:       "Food & Drink - Other",
	Category_ADHD_4:       "A.D.D.",
	Category_AIDS_4:       "AIDS/HIV",
	Category_ALLERGY_4:    "Allergies",
	Category_ALTMED_4:     "Alternative Medicine",
	Category_ARTHRITIS_4:  "Arthritis",
	Category_ASTHMA_4:     "Asthma",
	Category_AUTISM_4:     "Autism/PDD",
	Category_BIPOLAR_4:    "Bipolar Disorder",
	Category_TUMOR_4:      "Brain Tumor",
	Category_CANCER_4:     "Cancer",
	Category_KIDHEALTH_4:  "Children's Health",
	Category_CHOLESTER_4:  "Cholesterol",
	Category_FATIGUE_4:    "Chronic Fatigue",
	Category_PAIN_4:       "Chronic Pain",
	Category_FLU_4:        "Cold & Flu",
	Category_PSURGERY_4:   "Cosmetic Surgery",
	Category_DEAFNESS_4:   "Deafness",
	Category_DENTAL_4:     "Dental Care",
	Category_DEPRESSION_4: "Depression",
	Category_DERMA_4:      "Dermatology",
	Category_DIABETES_4:   "Diabetes",
	Category_DISORDER_4:   "Disorders",
	Category_EPILEPSY_4:   "Epilepsy",
	Category_EXERCISE_4:   "Exercise",
	Category_GERD_4:       "GERD/Acid Reflux",
	Category_MIGRAINE_4:   "Headaches/Migraines",
	Category_CARDIO_4:     "Heart Disease",
	Category_HERB_4:       "Herbs for Health",
	Category_HOLISTIC_4:   "Holistic Healing",
	Category_IBS_4:        "IBS/Crohn’s Disease",
	Category_ABUSE_4:      "Incest/Abuse Support",
	Category_INCNTNENCE_4: "Incontinence",
	Category_INFERTILE_4:  "Infertility",
	Category_MENHEALTH_4:  "Men’s Health",
	Category_DIET_4:       "Nutrition & Diet",
	Category_ORTHO_4:      "Orthopedics",
	Category_ANXIETY_4:    "Panic/Anxiety",
	Category_PEDIA_4:      "Pediatrics",
	Category_RX_4:         "Pharmaceuticals",
	Category_PHYTHERAPY_4: "Physical Therapy",
	Category_PSYCH_4:      "Psychology/Psychiatry",
	Category_ADDICTION_4:  "Self-help & Addiction",
	Category_SRHEALTH_4:   "Senior Health",
	Category_SEXUALITY_4:  "Sexuality",
	Category_SLEEP_4:      "Sleep Disorders",
	Category_QUITSMOKE_4:  "Smoking Cessation",
	Category_VITAMINS_4:   "Supplements & Compounds",
	Category_SYNDROME_4:   "Syndrome",
	Category_THYROID_4:    "Thyroid Disease",
	Category_WEIGHTLOSS_4: "Weight Loss",
	Category_FEMHEALTH_4:  "Women’s Health",
	Category_HEALTH_4:     "Health - Other",
	Category_ARTTECH_4:    "Art/Technology",
	Category_ARTCRAFT_4:   "Arts & Crafts",
	Category_BEADWORK_4:   "Beadwork",
	Category_BIRDWATCH_4:  "Birdwatching",
	Category_PUZZLE_4:     "Board Games/Puzzles",
	Category_CANDLE_4:     "Candle & Soap Making",
	Category_CARDGAME_4:   "Card Games",
	Category_CARTOON_4:    "Cartoons & Anime",
	Category_CHESS_4:      "Chess",
	Category_CIGAR_4:      "Cigars",
	Category_COLLECT_4:    "Collecting",
	Category_COMIC_4:      "Comic Books",
	Category_DRAW_4:       "Drawing/Sketching",
	Category_WRITE_4:      "Freelance Writing",
	Category_GENEALOGY_4:  "Genealogy",
	Category_PUBLISH_4:    "Getting Published",
	Category_GUITAR_4:     "Guitar",
	Category_HOMERECORD_4: "Home Recording",
	Category_PATENT_4:     "Investors & Patents",
	Category_MAKEJEWEL_4:  "Jewelry Making",
	Category_MAGIC_4:      "Magic & Illusion",
	Category_NEEDLEWORK_4: "Needlework",
	Category_PAINT_4:      "Painting",
	Category_PHOTOHOB_4:   "Photography",
	Category_RADIO_4:      "Radio",
	Category_RPG_4:        "Roleplaying Games",
	Category_SCIFI_4:      "Sci-Fi & Fantasy",
	Category_SCRAPBOOK_4:  "Scrapbooking",
	Category_SCREENWRT_4:  "Screenwriting",
	Category_STAMP_4:      "Stamps & Coins",
	Category_THEME_4:      "Themes",
	Category_VIDEOGAME_4:  "Video & Computer Games",
	Category_WOODWORK_4:   "Woodworking",
	Category_HOBBY_4:      "Hobbies & Interests - Other",
	Category_APPLIANCE_4:  "Appliances",
	Category_ENTHOME_4:    "Entertaining",
	Category_ECOSAFETY_4:  "Environmental Safety",
	Category_GARDEN_4:     "Gardening",
	Category_HOMEREPAIR_4: "Home Repair",
	Category_HOMECINEMA_4: "Home Theater",
	Category_INTERIOR_4:   "Interior Decorating",
	Category_LANDSCAPE_4:  "Landscaping",
	Category_REMODEL_4:    "Remodeling & Construction",
	Category_HOME_4:       "Home & Garden - Other",
	Category_GAMES_4:      "Games",
	Category_KIDSPAGE_4:   "Kid’s Pages",
	Category_TOYS_4:       "Toys",
	Category_KIDS_4:       "Kids - Other",
	Category_DATING_4:     "Dating & Relationships",
	Category_DIVORCE_4:    "Divorce Support",
	Category_ETHNIC_4:     "Ethnic Specific",
	Category_MARRIAGE_4:   "Marriage",
	Category_PARKS_4:      "Parks, Rec Facilities & Gyms",
	Category_SENIOR_4:     "Senior Living",
	Category_TEENS_4:      "Teens",
	Category_WEDDING_4:    "Weddings",
	Category_LIFESTYLE_4:  "Lifestyle - Other",
	Category_ADFRAUD_4:    "Ad Fraud",
	Category_BOTS_4:       "Botnet",
	Category_CANDC_4:      "Command and Control Centers",
	Category_COMPR_4:      "Compromised & Links To Malware",
	Category_MALHOME_4:    "Malware Call-Home",
	Category_MAL_4:        "Malware Distribution Point",
	Category_FRAUD_4:      "Phishing/Fraud",
	Category_SPAM_4:       "Spam URLs",
	Category_SPYWARE_4:    "Spyware & Questionable Software",
	Category_CDN_4:        "Content Server",
	Category_BLANK_4:      "No Content Found",
	Category_PARKED_4:     "Parked & For Sale Domains",
	Category_PRIVIP_4:     "Private IP Address",
	Category_BROKEN_4:     "Unreachable",
	Category_MISC_4:       "Miscellaneous - Other",
	Category_IMGSEARCH_4:  "Image Search",
	Category_INTLNEWS_4:   "International News",
	Category_LOCALNEWS_4:  "Local News",
	Category_MAGAZINES_4:  "Magazines",
	Category_NATLNEWS_4:   "National News",
	Category_PORTAL_4:     "Portal Sites",
	Category_SEARCH_4:     "Search Engines",
	Category_NEWS_4:       "News, Portal & Search - Other",
	Category_PAYTOSURF_4:  "Pay To Surf",
	Category_ADWARE_4:     "Online Ads - Other",
	Category_AQUARIUM_4:   "Aquariums",
	Category_BIRD_4:       "Birds",
	Category_CAT_4:        "Cats",
	Category_DOG_4:        "Dogs",
	Category_BIGANIMALS_4: "Large Animals",
	Category_REPTILE_4:    "Reptiles",
	Category_VETMED_4:     "Veterinary Medicine",
	Category_PETS_4:       "Pets - Other",
	Category_ADVOCACY_4:   "Advocacy Groups & Trade Associations",
	Category_COMMENTARY_4: "Commentary",
	Category_GOVSPONSOR_4: "Government Sponsored",
	Category_IMMIGRANT_4:  "Immigration",
	Category_LEGAL_4:      "Legal Issues",
	Category_CHARITY_4:    "Philanthropic Organizations",
	Category_POLITICS_4:   "Politics",
	Category_CLUBS_4:      "Social & Affiliation Organizations",
	Category_USRESOURCE_4: "U.S. Government Resources",
	Category_GOV_4:        "Public, Government & Law - Other",
	Category_APARTMENT_4:  "Apartments",
	Category_ARCHI_4:      "Architects",
	Category_BNSHOME_4:    "Buying/Selling Homes",
	Category_PROP_4:       "Real Estate - Other",
	Category_ALTRELGN_4:   "Alternative Religions",
	Category_ATHEISM_4:    "Atheism & Agnosticism",
	Category_BUDDHISM_4:   "Buddhism",
	Category_CATHOLIC_4:   "Catholicism",
	Category_CHRISTIAN_4:  "Christianity",
	Category_HINDU_4:      "Hinduism",
	Category_ISLAM_4:      "Islam",
	Category_JUDAISM_4:    "Judaism",
	Category_LDS_4:        "Latter-Day Saints",
	Category_CULT_4:       "Non-traditional Religion & Occult",
	Category_PAGAN_4:      "Pagan/Wiccan",
	Category_RELIGION_4:   "Religion - Other",
	Category_ANATOMY_4:    "Anatomy",
	Category_ASTROLOGY_4:  "Astrology & Horoscopes",
	Category_BIOLOGY_4:    "Biology",
	Category_BOTANY_4:     "Botany",
	Category_CHEMISTRY_4:  "Chemistry",
	Category_GEOGRAPHY_4:  "Geography",
	Category_GEOLOGY_4:    "Geology",
	Category_PARANORMAL_4: "Paranormal Phenomena",
	Category_PHYSICS_4:    "Physics",
	Category_ASTRONOMY_4:  "Space/Astronomy",
	Category_WEATHER_4:    "Weather",
	Category_SCIENCE_4:    "Science - Other",
	Category_P2PSHOP_4:    "Auctions & Marketplaces",
	Category_CATALOG_4:    "Catalogs",
	Category_SURVEY_4:     "Contests & Surveys",
	Category_COUPON_4:     "Coupons",
	Category_SHOPENGINE_4: "Engines",
	Category_ONLINESHOP_4: "Online Shopping",
	Category_SHOPSEARCH_4: "Product Reviews & Price Comparisons",
	Category_SHOP_4:       "Shopping - Other",
	Category_AUTORACE_4:   "Auto Racing",
	Category_BASEBALL_4:   "Baseball",
	Category_BICYCLING_4:  "Bicycling",
	Category_BODYBUILD_4:  "Bodybuilding",
	Category_BOXING_4:     "Boxing",
	Category_KAYAK_4:      "Canoeing/Kayaking",
	Category_CHEERLEAD_4:  "Cheerleeding",
	Category_CLIMB_4:      "Climbing",
	Category_CRICKET_4:    "Cricket",
	Category_FIGSKATE_4:   "Figure Skating",
	Category_FLYFISHING_4: "Fly Fishing",
	Category_FOOTBALL_4:   "Football",
	Category_FRESHFISH_4:  "Freshwater Fishing",
	Category_GAMEFISH_4:   "Game & Fish",
	Category_GOLF_4:       "Golf",
	Category_HORSERACE_4:  "Horse Racing",
	Category_HORSES_4:     "Horses",
	Category_INSKATE_4:    "Inline Skating",
	Category_MARTIALART_4: "Martial Arts",
	Category_BIKING_4:     "Mountain Biking",
	Category_NASCAR_4:     "NASCAR Racing",
	Category_OLYMPICS_4:   "Olympics",
	Category_PAINTBALL_4:  "Paintball",
	Category_MOTORACE_4:   "Power & Motorcycles",
	Category_PROBASKET_4:  "Pro Basketball",
	Category_ICEHOCKEY_4:  "Pro Ice Hockey",
	Category_RODEO_4:      "Rodeo",
	Category_RUGBY_4:      "Rugby",
	Category_RUN_4:        "Running/Jogging",
	Category_SAIL_4:       "Sailing",
	Category_SALTFISH_4:   "Saltwater Fishing",
	Category_SCUBA_4:      "Scuba Diving",
	Category_SKATEBOARD_4: "Skateboarding",
	Category_SKI_4:        "Skiing",
	Category_SNOWBOARD_4:  "Snowboarding",
	Category_HUNT_4:       "Sport Hunting",
	Category_SURF_4:       "Surfing/Bodyboarding",
	Category_SWIM_4:       "Swimming",
	Category_PINGPONG_4:   "Table Tennis/Ping-Pong",
	Category_TENNIS_4:     "Tennis",
	Category_VOLLEYBALL_4: "Volleyball",
	Category_WALK_4:       "Walking",
	Category_WATERSKI_4:   "Waterski/Wakeboard",
	Category_SOCCER_4:     "World Soccer",
	Category_SPORTS_4:     "Sports - Other",
	Category_GRAPHICS3D_4: "3-D Graphics",
	Category_ANIMATION_4:  "Animation",
	Category_ANTIVIRUS_4:  "Antivirus Software",
	Category_CLANG_4:      "C/C++",
	Category_CAMERA_4:     "Cameras & Camcorders",
	Category_COMPCERT_4:   "Computer Certification",
	Category_COMPNET_4:    "Computer Networking",
	Category_PERIPHERAL_4: "Computer Peripherals",
	Category_COMPREVIEW_4: "Computer Reviews",
	Category_DATABASE_4:   "Databases",
	Category_DESKPUB_4:    "Desktop Publishing",
	Category_DESKVID_4:    "Desktop Video",
	Category_TECHENT_4:    "Entertainment",
	Category_REPOS_4:      "File Repositories",
	Category_GRAPHICS_4:   "Graphics Software",
	Category_DVD_4:        "Home Video/DVD",
	Category_COMPSEC_4:    "Information Security",
	Category_VOIP_4:       "Internet Phone & VOIP",
	Category_INTERNET_4:   "Internet Technology",
	Category_JAVA_4:       "Java",
	Category_JAVASCRIPT_4: "Javascript",
	Category_LINUX_4:      "Linux",
	Category_MAC_4:        "Mac OS",
	Category_MACSUPPORT_4: "Mac Support",
	Category_MOBILE_4:     "Mobile Phones",
	Category_MP3_4:        "MP3/MIDI",
	Category_NETCON_4:     "Net Conferencing",
	Category_NETBEG_4:     "Net for Beginners",
	Category_NETSEC_4:     "Network Security",
	Category_OFFICE_4:     "Online Information Management",
	Category_PDA_4:        "Palmtops/PDAs",
	Category_PCSUPPORT_4:  "PC Support",
	Category_P2P_4:        "Peer-to-Peer",
	Category_STORAGE_4:    "Personal Storage",
	Category_PORTABLE_4:   "Portable",
	Category_VPN_4:        "Remote Access",
	Category_FREEWARE_4:   "Shareware/Freeware",
	Category_UNIX_4:       "Unix",
	Category_UTILITIES_4:  "Utilities",
	Category_VBASIC_4:     "Visual Basic",
	Category_CLIPART_4:    "Web Clip Art",
	Category_WEBDESIGN_4:  "Web Design/HTML",
	Category_ISP_4:        "Web Hosting, ISP & Telco",
	Category_WINDOWS_4:    "Windows",
	Category_TECH_4:       "Technology - Other",
	Category_ADVENTURE_4:  "Adventure Travel",
	Category_AFRICA_4:     "Africa",
	Category_AIRTRAVEL_4:  "Air Travel",
	Category_AUSTRALIA_4:  "Australia & New Zealand",
	Category_BNB_4:        "Bed & Breakfast",
	Category_BDGTTRAVEL_4: "Budget Travel",
	Category_BIZTRAVEL_4:  "Business Travel",
	Category_USTRAVEL_4:   "By US Locale",
	Category_CAMP_4:       "Camping",
	Category_CANADA_4:     "Canada",
	Category_CARIBBEAN_4:  "Caribbean",
	Category_CRUISE_4:     "Cruises",
	Category_EASTEUROPE_4: "Eastern Europe",
	Category_EUROPE_4:     "Europe",
	Category_FRANCE_4:     "France",
	Category_GREECE_4:     "Greece",
	Category_GETAWAY_4:    "Honeymoons/Getaways",
	Category_HOTEL_4:      "Hotels",
	Category_ITALY_4:      "Italy",
	Category_JAPAN_4:      "Japan",
	Category_MEXICO_4:     "Mexico & Central America",
	Category_NATLPARKS_4:  "National Parks",
	Category_NAVIGATION_4: "Navigation",
	Category_SAMERICA_4:   "South America",
	Category_SPA_4:        "Spas",
	Category_THEMEPARK_4:  "Theme Parks",
	Category_KIDTRAVEL_4:  "Traveling with Kids",
	Category_UKTRAVEL_4:   "United Kingdom",
	Category_TRAVEL_4:     "Travel - Other",
}

// Long returns the category long name
func (c Category) Long() string {
	return CategoryLong[c]
}
