[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.0.1"

[[constraint]]
  name = "zvelo.io/zmage"
  version = "3.0.0"

[[constraint]]
  name = "github.com/magefile/mage"
  version = "2.0.1"
