# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zvelo/msg/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zvelo.msg import dataset_pb2 as zvelo_dot_msg_dot_dataset__pb2
from zvelo.msg import status_pb2 as zvelo_dot_msg_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zvelo/msg/query.proto',
  package='zvelo.msg',
  syntax='proto3',
  serialized_pb=_b('\n\x15zvelo/msg/query.proto\x12\tzvelo.msg\x1a\x17zvelo/msg/dataset.proto\x1a\x16zvelo/msg/status.proto\"\x1f\n\tRequestID\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"g\n\x0bQueryStatus\x12\x10\n\x08\x63omplete\x18\x01 \x01(\x08\x12 \n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.zvelo.msg.Status\x12\x12\n\nfetch_code\x18\x03 \x01(\x05\x12\x10\n\x08location\x18\x04 \x01(\t\"\xae\x01\n\x0bQueryResult\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12,\n\x10response_dataset\x18\x07 \x01(\x0b\x32\x12.zvelo.msg.DataSet\x12\x0b\n\x03url\x18\x08 \x01(\t\x12,\n\x0cquery_status\x18\n \x01(\x0b\x32\x16.zvelo.msg.QueryStatusJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\t\x10\n\"\x92\x01\n\nURLContent\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x31\n\x06header\x18\x03 \x03(\x0b\x32!.zvelo.msg.URLContent.HeaderEntry\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x1a-\n\x0bHeaderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x01\x10\x02\"\x85\x01\n\rQueryRequests\x12\x0b\n\x03url\x18\x01 \x03(\t\x12&\n\x07\x63ontent\x18\x02 \x03(\x0b\x32\x15.zvelo.msg.URLContent\x12\x10\n\x08\x63\x61llback\x18\x03 \x01(\t\x12\'\n\x07\x64\x61taset\x18\x05 \x03(\x0e\x32\x16.zvelo.msg.DataSetTypeJ\x04\x08\x04\x10\x05\"N\n\nQueryReply\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12 \n\x05\x65rror\x18\x04 \x01(\x0b\x32\x11.zvelo.msg.StatusJ\x04\x08\x01\x10\x02J\x04\x08\x03\x10\x04\"4\n\x0cQueryReplies\x12$\n\x05reply\x18\x01 \x03(\x0b\x32\x15.zvelo.msg.QueryReplyB\x0eZ\x0czvelo.io/msgb\x06proto3')
  ,
  dependencies=[zvelo_dot_msg_dot_dataset__pb2.DESCRIPTOR,zvelo_dot_msg_dot_status__pb2.DESCRIPTOR,])




_REQUESTID = _descriptor.Descriptor(
  name='RequestID',
  full_name='zvelo.msg.RequestID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='zvelo.msg.RequestID.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=116,
)


_QUERYSTATUS = _descriptor.Descriptor(
  name='QueryStatus',
  full_name='zvelo.msg.QueryStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='complete', full_name='zvelo.msg.QueryStatus.complete', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='zvelo.msg.QueryStatus.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fetch_code', full_name='zvelo.msg.QueryStatus.fetch_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='zvelo.msg.QueryStatus.location', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=221,
)


_QUERYRESULT = _descriptor.Descriptor(
  name='QueryResult',
  full_name='zvelo.msg.QueryResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='zvelo.msg.QueryResult.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_dataset', full_name='zvelo.msg.QueryResult.response_dataset', index=1,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='zvelo.msg.QueryResult.url', index=2,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_status', full_name='zvelo.msg.QueryResult.query_status', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=398,
)


_URLCONTENT_HEADERENTRY = _descriptor.Descriptor(
  name='HeaderEntry',
  full_name='zvelo.msg.URLContent.HeaderEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='zvelo.msg.URLContent.HeaderEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='zvelo.msg.URLContent.HeaderEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=541,
)

_URLCONTENT = _descriptor.Descriptor(
  name='URLContent',
  full_name='zvelo.msg.URLContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='zvelo.msg.URLContent.url', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='zvelo.msg.URLContent.header', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='zvelo.msg.URLContent.content', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_URLCONTENT_HEADERENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=547,
)


_QUERYREQUESTS = _descriptor.Descriptor(
  name='QueryRequests',
  full_name='zvelo.msg.QueryRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='zvelo.msg.QueryRequests.url', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='zvelo.msg.QueryRequests.content', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callback', full_name='zvelo.msg.QueryRequests.callback', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='zvelo.msg.QueryRequests.dataset', index=3,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=683,
)


_QUERYREPLY = _descriptor.Descriptor(
  name='QueryReply',
  full_name='zvelo.msg.QueryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='zvelo.msg.QueryReply.request_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='zvelo.msg.QueryReply.error', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=763,
)


_QUERYREPLIES = _descriptor.Descriptor(
  name='QueryReplies',
  full_name='zvelo.msg.QueryReplies',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='zvelo.msg.QueryReplies.reply', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=765,
  serialized_end=817,
)

_QUERYSTATUS.fields_by_name['error'].message_type = zvelo_dot_msg_dot_status__pb2._STATUS
_QUERYRESULT.fields_by_name['response_dataset'].message_type = zvelo_dot_msg_dot_dataset__pb2._DATASET
_QUERYRESULT.fields_by_name['query_status'].message_type = _QUERYSTATUS
_URLCONTENT_HEADERENTRY.containing_type = _URLCONTENT
_URLCONTENT.fields_by_name['header'].message_type = _URLCONTENT_HEADERENTRY
_QUERYREQUESTS.fields_by_name['content'].message_type = _URLCONTENT
_QUERYREQUESTS.fields_by_name['dataset'].enum_type = zvelo_dot_msg_dot_dataset__pb2._DATASETTYPE
_QUERYREPLY.fields_by_name['error'].message_type = zvelo_dot_msg_dot_status__pb2._STATUS
_QUERYREPLIES.fields_by_name['reply'].message_type = _QUERYREPLY
DESCRIPTOR.message_types_by_name['RequestID'] = _REQUESTID
DESCRIPTOR.message_types_by_name['QueryStatus'] = _QUERYSTATUS
DESCRIPTOR.message_types_by_name['QueryResult'] = _QUERYRESULT
DESCRIPTOR.message_types_by_name['URLContent'] = _URLCONTENT
DESCRIPTOR.message_types_by_name['QueryRequests'] = _QUERYREQUESTS
DESCRIPTOR.message_types_by_name['QueryReply'] = _QUERYREPLY
DESCRIPTOR.message_types_by_name['QueryReplies'] = _QUERYREPLIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestID = _reflection.GeneratedProtocolMessageType('RequestID', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTID,
  __module__ = 'zvelo.msg.query_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.RequestID)
  ))
_sym_db.RegisterMessage(RequestID)

QueryStatus = _reflection.GeneratedProtocolMessageType('QueryStatus', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSTATUS,
  __module__ = 'zvelo.msg.query_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.QueryStatus)
  ))
_sym_db.RegisterMessage(QueryStatus)

QueryResult = _reflection.GeneratedProtocolMessageType('QueryResult', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESULT,
  __module__ = 'zvelo.msg.query_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.QueryResult)
  ))
_sym_db.RegisterMessage(QueryResult)

URLContent = _reflection.GeneratedProtocolMessageType('URLContent', (_message.Message,), dict(

  HeaderEntry = _reflection.GeneratedProtocolMessageType('HeaderEntry', (_message.Message,), dict(
    DESCRIPTOR = _URLCONTENT_HEADERENTRY,
    __module__ = 'zvelo.msg.query_pb2'
    # @@protoc_insertion_point(class_scope:zvelo.msg.URLContent.HeaderEntry)
    ))
  ,
  DESCRIPTOR = _URLCONTENT,
  __module__ = 'zvelo.msg.query_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.URLContent)
  ))
_sym_db.RegisterMessage(URLContent)
_sym_db.RegisterMessage(URLContent.HeaderEntry)

QueryRequests = _reflection.GeneratedProtocolMessageType('QueryRequests', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUESTS,
  __module__ = 'zvelo.msg.query_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.QueryRequests)
  ))
_sym_db.RegisterMessage(QueryRequests)

QueryReply = _reflection.GeneratedProtocolMessageType('QueryReply', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREPLY,
  __module__ = 'zvelo.msg.query_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.QueryReply)
  ))
_sym_db.RegisterMessage(QueryReply)

QueryReplies = _reflection.GeneratedProtocolMessageType('QueryReplies', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREPLIES,
  __module__ = 'zvelo.msg.query_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.QueryReplies)
  ))
_sym_db.RegisterMessage(QueryReplies)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\014zvelo.io/msg'))
_URLCONTENT_HEADERENTRY.has_options = True
_URLCONTENT_HEADERENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
