# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zvelo/msg/suggest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zvelo.msg import dataset_pb2 as zvelo_dot_msg_dot_dataset__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zvelo/msg/suggest.proto',
  package='zvelo.msg',
  syntax='proto3',
  serialized_pb=_b('\n\x17zvelo/msg/suggest.proto\x12\tzvelo.msg\x1a\x17zvelo/msg/dataset.proto\">\n\nSuggestion\x12\x0b\n\x03url\x18\x01 \x01(\t\x12#\n\x07\x64\x61taset\x18\x02 \x01(\x0b\x32\x12.zvelo.msg.DataSetB\x0eZ\x0czvelo.io/msgb\x06proto3')
  ,
  dependencies=[zvelo_dot_msg_dot_dataset__pb2.DESCRIPTOR,])




_SUGGESTION = _descriptor.Descriptor(
  name='Suggestion',
  full_name='zvelo.msg.Suggestion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='zvelo.msg.Suggestion.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='zvelo.msg.Suggestion.dataset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=125,
)

_SUGGESTION.fields_by_name['dataset'].message_type = zvelo_dot_msg_dot_dataset__pb2._DATASET
DESCRIPTOR.message_types_by_name['Suggestion'] = _SUGGESTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Suggestion = _reflection.GeneratedProtocolMessageType('Suggestion', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTION,
  __module__ = 'zvelo.msg.suggest_pb2'
  # @@protoc_insertion_point(class_scope:zvelo.msg.Suggestion)
  ))
_sym_db.RegisterMessage(Suggestion)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\014zvelo.io/msg'))
# @@protoc_insertion_point(module_scope)
