{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "zveloAPI",
    "contact": {
      "name": "zvelo",
      "url": "https://zvelo.com",
      "email": "support@zvelo.com"
    },
    "license": {
      "name": "zvelo Proprietary"
    },
    "version": "1"
  },
  "host": "api.zvelo.com",
  "basePath": "/",
  "paths": {
    "/v1/overrides": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "List overrides",
        "operationId": "OverrideListV1",
        "security": [
          {
            "authorization": [
              "zvelo.override"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "API"
        ],
        "summary": "Add or update an override",
        "operationId": "OverrideAddV1",
        "security": [
          {
            "authorization": [
              "zvelo.override"
            ]
          }
        ]
      }
    },
    "/v1/overrides/expired": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "List expired overrides of the given type",
        "operationId": "OverrideListExpiredV1",
        "security": [
          {
            "authorization": [
              "zvelo.override"
            ]
          }
        ]
      }
    },
    "/v1/overrides/matching/{url}": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "Find the override that would match a given URL",
        "operationId": "OverrideMatchingV1",
        "security": [
          {
            "authorization": [
              "zvelo.override"
            ]
          }
        ]
      }
    },
    "/v1/overrides/{url}": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "Get an override by its base URL",
        "operationId": "OverrideGetV1",
        "security": [
          {
            "authorization": [
              "zvelo.override"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "API"
        ],
        "summary": "Delete an existing override",
        "operationId": "OverrideDeleteV1",
        "security": [
          {
            "authorization": [
              "zvelo.override"
            ]
          }
        ]
      }
    },
    "/v1/queries/content": {
      "post": {
        "tags": [
          "API"
        ],
        "summary": "Create new content query",
        "operationId": "QueryContentV1",
        "security": [
          {
            "authorization": [
              "zvelo.dataset"
            ]
          }
        ]
      }
    },
    "/v1/queries/content/{request_id}": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "Results of active or unexpired query",
        "operationId": "QueryContentResultV1",
        "security": [
          {
            "authorization": [
              "zvelo.dataset"
            ]
          }
        ]
      }
    },
    "/v1/queries/url": {
      "post": {
        "tags": [
          "API"
        ],
        "summary": "Create new URL query",
        "operationId": "QueryURLV1",
        "security": [
          {
            "authorization": [
              "zvelo.dataset"
            ]
          }
        ]
      }
    },
    "/v1/queries/url/{request_id}": {
      "get": {
        "tags": [
          "API"
        ],
        "summary": "Results of active or unexpired query",
        "operationId": "QueryURLResultV1",
        "security": [
          {
            "authorization": [
              "zvelo.dataset"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "authorization": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://auth.zvelo.com/oauth2/auth",
      "tokenUrl": "https://auth.zvelo.com/oauth2/token",
      "scopes": {
        "zvelo.dataset": "Access zvelo Datasets"
      }
    }
  }
}