// Code generated by protoc-gen-go.
// source: zvelo/msg/zvelo_api.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type QueryURLRequests struct {
	Url            []string      `protobuf:"bytes,1,rep,name=url" json:"url,omitempty"`
	Dataset        []DataSetType `protobuf:"varint,2,rep,packed,name=dataset,enum=zvelo.msg.DataSetType" json:"dataset,omitempty"`
	Callback       string        `protobuf:"bytes,3,opt,name=callback" json:"callback,omitempty"`
	Poll           bool          `protobuf:"varint,4,opt,name=poll" json:"poll,omitempty"`
	PartialResults bool          `protobuf:"varint,5,opt,name=partial_results,json=partialResults" json:"partial_results,omitempty"`
	Accept         string        `protobuf:"bytes,6,opt,name=accept" json:"accept,omitempty"`
}

func (m *QueryURLRequests) Reset()                    { *m = QueryURLRequests{} }
func (m *QueryURLRequests) String() string            { return proto.CompactTextString(m) }
func (*QueryURLRequests) ProtoMessage()               {}
func (*QueryURLRequests) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *QueryURLRequests) GetUrl() []string {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *QueryURLRequests) GetDataset() []DataSetType {
	if m != nil {
		return m.Dataset
	}
	return nil
}

func (m *QueryURLRequests) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *QueryURLRequests) GetPoll() bool {
	if m != nil {
		return m.Poll
	}
	return false
}

func (m *QueryURLRequests) GetPartialResults() bool {
	if m != nil {
		return m.PartialResults
	}
	return false
}

func (m *QueryURLRequests) GetAccept() string {
	if m != nil {
		return m.Accept
	}
	return ""
}

type QueryContentRequests struct {
	Content        []*QueryContentRequests_URLContent `protobuf:"bytes,1,rep,name=content" json:"content,omitempty"`
	Dataset        []DataSetType                      `protobuf:"varint,2,rep,packed,name=dataset,enum=zvelo.msg.DataSetType" json:"dataset,omitempty"`
	Callback       string                             `protobuf:"bytes,3,opt,name=callback" json:"callback,omitempty"`
	Poll           bool                               `protobuf:"varint,4,opt,name=poll" json:"poll,omitempty"`
	PartialResults bool                               `protobuf:"varint,5,opt,name=partial_results,json=partialResults" json:"partial_results,omitempty"`
	Accept         string                             `protobuf:"bytes,6,opt,name=accept" json:"accept,omitempty"`
}

func (m *QueryContentRequests) Reset()                    { *m = QueryContentRequests{} }
func (m *QueryContentRequests) String() string            { return proto.CompactTextString(m) }
func (*QueryContentRequests) ProtoMessage()               {}
func (*QueryContentRequests) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *QueryContentRequests) GetContent() []*QueryContentRequests_URLContent {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *QueryContentRequests) GetDataset() []DataSetType {
	if m != nil {
		return m.Dataset
	}
	return nil
}

func (m *QueryContentRequests) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *QueryContentRequests) GetPoll() bool {
	if m != nil {
		return m.Poll
	}
	return false
}

func (m *QueryContentRequests) GetPartialResults() bool {
	if m != nil {
		return m.PartialResults
	}
	return false
}

func (m *QueryContentRequests) GetAccept() string {
	if m != nil {
		return m.Accept
	}
	return ""
}

type QueryContentRequests_URLContent struct {
	// Use a unique id if content has no url, to link response to request.
	Id      string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url     string            `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Header  map[string]string `protobuf:"bytes,3,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content string            `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *QueryContentRequests_URLContent) Reset()         { *m = QueryContentRequests_URLContent{} }
func (m *QueryContentRequests_URLContent) String() string { return proto.CompactTextString(m) }
func (*QueryContentRequests_URLContent) ProtoMessage()    {}
func (*QueryContentRequests_URLContent) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{1, 0}
}

func (m *QueryContentRequests_URLContent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryContentRequests_URLContent) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *QueryContentRequests_URLContent) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QueryContentRequests_URLContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type QueryReply struct {
	Status     *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	RequestId  string  `protobuf:"bytes,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Url        string  `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	TrackingId string  `protobuf:"bytes,4,opt,name=tracking_id,json=trackingId" json:"tracking_id,omitempty"`
	// the target of QueryStatus, to ensure that the QueryStatus call
	// goes to the same cluster as the original call.
	// Will only be set if user set p=true in request.
	StatusUrl string `protobuf:"bytes,5,opt,name=status_url,json=statusUrl" json:"status_url,omitempty"`
}

func (m *QueryReply) Reset()                    { *m = QueryReply{} }
func (m *QueryReply) String() string            { return proto.CompactTextString(m) }
func (*QueryReply) ProtoMessage()               {}
func (*QueryReply) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *QueryReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QueryReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *QueryReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *QueryReply) GetTrackingId() string {
	if m != nil {
		return m.TrackingId
	}
	return ""
}

func (m *QueryReply) GetStatusUrl() string {
	if m != nil {
		return m.StatusUrl
	}
	return ""
}

type QueryReplies struct {
	Replies []*QueryReply `protobuf:"bytes,1,rep,name=replies" json:"replies,omitempty"`
	Status  *Status       `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *QueryReplies) Reset()                    { *m = QueryReplies{} }
func (m *QueryReplies) String() string            { return proto.CompactTextString(m) }
func (*QueryReplies) ProtoMessage()               {}
func (*QueryReplies) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *QueryReplies) GetReplies() []*QueryReply {
	if m != nil {
		return m.Replies
	}
	return nil
}

func (m *QueryReplies) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryURLRequests)(nil), "zvelo.msg.QueryURLRequests")
	proto.RegisterType((*QueryContentRequests)(nil), "zvelo.msg.QueryContentRequests")
	proto.RegisterType((*QueryContentRequests_URLContent)(nil), "zvelo.msg.QueryContentRequests.URLContent")
	proto.RegisterType((*QueryReply)(nil), "zvelo.msg.QueryReply")
	proto.RegisterType((*QueryReplies)(nil), "zvelo.msg.QueryReplies")
}

func init() { proto.RegisterFile("zvelo/msg/zvelo_api.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x53, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0x49, 0x9b, 0x6e, 0x4f, 0x97, 0xba, 0x0e, 0x6b, 0x1d, 0x03, 0x62, 0xe9, 0x8d, 0xd5,
	0x8b, 0x54, 0x2a, 0x88, 0x7a, 0xa9, 0x2b, 0xb8, 0xb0, 0x08, 0xce, 0xda, 0x1b, 0x6f, 0xca, 0x6c,
	0x32, 0xd4, 0xd8, 0xd9, 0x26, 0xce, 0x4c, 0x16, 0xe2, 0x13, 0xf9, 0x26, 0x3e, 0x80, 0xf8, 0x3e,
	0x92, 0x33, 0x93, 0x1f, 0x44, 0xd0, 0x5b, 0xef, 0xce, 0xf9, 0xce, 0xcf, 0x7c, 0xdf, 0x37, 0x33,
	0x70, 0xef, 0xeb, 0x8d, 0x90, 0xf9, 0xea, 0x5a, 0xef, 0x56, 0x18, 0x6d, 0x79, 0x91, 0xc5, 0x85,
	0xca, 0x4d, 0x4e, 0xc6, 0x08, 0xc4, 0xd7, 0x7a, 0x17, 0xdd, 0xed, 0xba, 0x52, 0x6e, 0xb8, 0x16,
	0xc6, 0xf6, 0x44, 0xb3, 0xae, 0xa0, 0x0d, 0x37, 0xa5, 0xb6, 0xf8, 0xe2, 0xbb, 0x07, 0x27, 0xef,
	0x4b, 0xa1, 0xaa, 0x0d, 0xbb, 0x60, 0xe2, 0x4b, 0x29, 0xb4, 0xd1, 0xe4, 0x04, 0x82, 0x52, 0x49,
	0xea, 0xcd, 0x83, 0xe5, 0x98, 0xd5, 0x21, 0x79, 0x02, 0x23, 0xb7, 0x8f, 0xfa, 0xf3, 0x60, 0x39,
	0x5d, 0xcf, 0xe2, 0xf6, 0xd0, 0xf8, 0x8c, 0x1b, 0x7e, 0x29, 0xcc, 0x87, 0xaa, 0x10, 0xac, 0x69,
	0x23, 0x11, 0x1c, 0x25, 0x5c, 0xca, 0x2b, 0x9e, 0xec, 0x69, 0x30, 0xf7, 0x96, 0x63, 0xd6, 0xe6,
	0x84, 0xc0, 0xa0, 0xc8, 0xa5, 0xa4, 0x83, 0xb9, 0xb7, 0x3c, 0x62, 0x18, 0x93, 0x87, 0x70, 0xab,
	0xe0, 0xca, 0x64, 0x5c, 0x6e, 0x95, 0xd0, 0xa5, 0x34, 0x9a, 0x0e, 0xb1, 0x3c, 0x75, 0x30, 0xb3,
	0x28, 0x99, 0x41, 0xc8, 0x93, 0x44, 0x14, 0x86, 0x86, 0xb8, 0xd6, 0x65, 0x8b, 0x9f, 0x01, 0x9c,
	0xa2, 0x92, 0xd7, 0xf9, 0xc1, 0x88, 0x83, 0x69, 0xd5, 0x9c, 0xc1, 0x28, 0xb1, 0x10, 0x2a, 0x9a,
	0xac, 0x1f, 0xf7, 0xb8, 0xff, 0x69, 0x22, 0xde, 0xb0, 0x8b, 0x06, 0x6a, 0x46, 0xff, 0x03, 0x07,
	0xa2, 0x1f, 0x1e, 0x40, 0x47, 0x9d, 0x4c, 0xc1, 0xcf, 0x52, 0xea, 0x61, 0x8b, 0x9f, 0xa5, 0xcd,
	0xad, 0xfa, 0x08, 0xe0, 0xad, 0xbe, 0x83, 0xf0, 0x93, 0xe0, 0xa9, 0x50, 0x34, 0x40, 0x63, 0x9e,
	0xfd, 0xbb, 0x31, 0xf1, 0x5b, 0x1c, 0x7c, 0x73, 0x30, 0xaa, 0x62, 0x6e, 0x0b, 0xa1, 0x9d, 0xd3,
	0x03, 0x3c, 0xa5, 0x49, 0xa3, 0x17, 0x30, 0xe9, 0x0d, 0xd4, 0x54, 0xf6, 0xa2, 0x72, 0xdc, 0xea,
	0x90, 0x9c, 0xc2, 0xf0, 0x86, 0xcb, 0x52, 0x38, 0x7a, 0x36, 0x79, 0xe9, 0x3f, 0xf7, 0x16, 0xdf,
	0x3c, 0x00, 0x24, 0xc3, 0x44, 0x21, 0x2b, 0xf2, 0x08, 0x42, 0xfb, 0x80, 0x71, 0x7a, 0xb2, 0xbe,
	0xdd, 0xe3, 0x7c, 0x89, 0x05, 0xe6, 0x1a, 0xc8, 0x7d, 0x00, 0x65, 0x99, 0x6f, 0xb3, 0xd4, 0x2d,
	0x1e, 0x3b, 0xe4, 0xbc, 0xf5, 0x23, 0xe8, 0xfc, 0x78, 0x00, 0x13, 0xa3, 0x78, 0xb2, 0xcf, 0x0e,
	0xbb, 0x7a, 0xc2, 0x6a, 0x80, 0x06, 0x3a, 0x4f, 0xeb, 0x8d, 0x76, 0xf7, 0xb6, 0x9e, 0x1c, 0xda,
	0x8d, 0x16, 0xd9, 0x28, 0xb9, 0xf8, 0x0c, 0xc7, 0x2d, 0xd3, 0x4c, 0x68, 0xb2, 0x82, 0x91, 0xb2,
	0xa1, 0x7b, 0x79, 0x77, 0x7e, 0x37, 0x18, 0x35, 0xb1, 0xa6, 0xab, 0x27, 0xce, 0xff, 0x8b, 0xb8,
	0x57, 0xd3, 0x8f, 0xc7, 0xb6, 0x96, 0xe1, 0xaf, 0xbe, 0x0a, 0xf1, 0x3f, 0x3f, 0xfd, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x62, 0x91, 0xf8, 0x68, 0x28, 0x04, 0x00, 0x00,
}
