---
version: 2

jobs:
  build:
    working_directory: /go/src/zvelo.io/msg

    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run:
          name: Install Test Dependencies
          command: |
            go get github.com/magefile/mage
            go get github.com/golang/dep/cmd/dep
            go get github.com/mattn/goveralls
            dep ensure
            touch msgpb/*.pb.go msgpb/*.pb.gw.go internal/static/static.go msg.protoset msg.swagger.json
            touch include/health/health.swagger.json
            echo "package health" > include/health/health.pb.go
            echo "package health" > include/health/health.pb.gw.go
      - run: mage -v checkImports
      - run:
          name: Calculate unit test coverage
          command: |
            mage -v coverOnly
            goveralls -v -coverprofile=.coverage-all.out -service circle-ci -repotoken ${COVERALLS_REPO_TOKEN} || true
