version: 2

jobs:
  build:
    working_directory: /go/src/zvelo.io/msg

    docker:
      - image: circleci/golang:latest

    environment:
      TEST_RESULTS: /tmp/test-results
      PROJECT: zvelo.io/msg
 
    steps:
      - checkout
      - run:
          name: Install Test Dependencies
          command: |
            go get -t -d -v ./...
            go get -v github.com/jstemmer/go-junit-report
            go get -v github.com/go-playground/overalls
            go get -v github.com/mattn/goveralls
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report < \"${TEST_RESULTS}/go-test.out\" > \"${TEST_RESULTS}/go-test-report.xml\"" EXIT
            go test -v -race 2>&1 | tee "${TEST_RESULTS}/go-test.out"
      - run:
          name: Calculate unit test coverage
          command: |
            overalls -project ${PROJECT}
            goveralls -v -coverprofile=overalls.coverprofile -service circle-ci -repotoken ${COVERALLS_REPO_TOKEN} || true
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
