---
version: 2

jobs:
  build:
    working_directory: /go/src/zvelo.io/msg

    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run:
          name: Install Dependencies
          environment:
            GO111MODULE: "off"
          command: |
            go get github.com/mattn/goveralls
            GO111MODULE=on go mod tidy
      - run:
          name: Test
          environment:
            GO111MODULE: "on"
          command: |
            go test -cover -race -coverprofile=.coverage-all.out ./...
            goveralls -v -coverprofile=.coverage-all.out -service circle-ci -repotoken ${COVERALLS_REPO_TOKEN} || true
