// Code generated by protoc-gen-go.
// source: categorization.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	categorization.proto
	dataset.proto
	query_result.proto
	status.proto
	zvelo-api.proto

It has these top-level messages:
	Categorization
	Categorizations
	DataSet
	QueryResult
	Status
	QueryURLRequests
	QueryContentRequests
	QueryReply
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Categorization struct {
	Url     string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Dataset *DataSet `protobuf:"bytes,2,opt,name=dataset" json:"dataset,omitempty"`
}

func (m *Categorization) Reset()                    { *m = Categorization{} }
func (m *Categorization) String() string            { return proto.CompactTextString(m) }
func (*Categorization) ProtoMessage()               {}
func (*Categorization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Categorization) GetDataset() *DataSet {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type Categorizations struct {
	Categorizations []*Categorization `protobuf:"bytes,1,rep,name=categorizations" json:"categorizations,omitempty"`
}

func (m *Categorizations) Reset()                    { *m = Categorizations{} }
func (m *Categorizations) String() string            { return proto.CompactTextString(m) }
func (*Categorizations) ProtoMessage()               {}
func (*Categorizations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Categorizations) GetCategorizations() []*Categorization {
	if m != nil {
		return m.Categorizations
	}
	return nil
}

func init() {
	proto.RegisterType((*Categorization)(nil), "msg.Categorization")
	proto.RegisterType((*Categorizations)(nil), "msg.Categorizations")
}

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x4e, 0x2c, 0x49,
	0x4d, 0xcf, 0x2f, 0xca, 0xac, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0xe2, 0x4d, 0x49, 0x2c, 0x49, 0x2c, 0x4e, 0x2d, 0x81, 0x88,
	0x29, 0x79, 0x71, 0xf1, 0x39, 0xa3, 0xa8, 0x15, 0x12, 0xe0, 0x62, 0x2e, 0x2d, 0xca, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0xd4, 0xb8, 0xd8, 0xa1, 0x9a, 0x24, 0x98, 0x80,
	0xa2, 0xdc, 0x46, 0x3c, 0x7a, 0x40, 0x93, 0xf4, 0x5c, 0x80, 0x62, 0xc1, 0xa9, 0x25, 0x41, 0x30,
	0x49, 0xa5, 0x00, 0x2e, 0x7e, 0x54, 0xb3, 0x8a, 0x85, 0x6c, 0xb9, 0xf8, 0x51, 0x9d, 0x52, 0x0c,
	0x34, 0x98, 0x19, 0x68, 0x84, 0x30, 0xd8, 0x08, 0x54, 0xe5, 0x41, 0xe8, 0x6a, 0x93, 0xd8, 0xc0,
	0x8e, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xcf, 0x78, 0x09, 0xd0, 0x00, 0x00, 0x00,
}
